### ISSUE TITLE
Bug? install.js failed due to incorrect dotnet.exe path matched

### ISSUE THREAD

**Issue by accelazh** [tjanczuk/edge-cs#12]
When installing edge-cs, which is a dependent package to my project, tools/install.js failed (see details for error message). It prevents package installation.

__Why failed__

In install.js, the `childProcess.spawn(dotnetPath, ..` ([line#27](https://github.com/tjanczuk/edge-cs/blob/master/tools/install.js#L27)) was not using the correct `dotnetPath`.

The `dotnetPath` being used was `C:\Program Files\dotnet`, which is a folder name. However `childProcess.spawn` expects a executable file name, i.e. `C:\Program Files\dotnet\dotnet.exe`.

Digging deeper, function `whereis` allows matching folder name. My environment variable setup made it match `C:\Program Files` earlier than `C:\Program Files\dotnet`.  (See details)

(I was using Windows 10.)

__Details & reproduce__

My environemnt %PATH%

```
...
C:\Program Files;  # This line made `whereis` match folder name rather than file name.
C:\Program Files\dotnet\;
...
```

My dotnet.exe path

```
C:\Program Files\dotnet\dotnet.exe
```

To reproduce. Below is the command that failed installation

```
E:\...\node_modules\edge-cs>node tools\install.js

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files\dotnet ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
    at ProcessTermError.ExtendableBuiltin (c:\corextcache\NPM.OnCloudbuild.1.0.5-xstore\bin\lib\cli.js:721:66)
    at ProcessTermError.MessageError (c:\corextcache\NPM.OnCloudbuild.1.0.5-xstore\bin\lib\cli.js:750:123)
    at new ProcessTermError (c:\corextcache\NPM.OnCloudbuild.1.0.5-xstore\bin\lib\cli.js:790:113)
    at ChildProcess.<anonymous> (c:\corextcache\NPM.OnCloudbuild.1.0.5-xstore\bin\lib\cli.js:25799:17)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

**Comment by accelazh** [comment]
For fixing, this patch limit `whereis` to only match file name rather than folder name.

---
 tools/install.js | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/tools/install.js b/tools/install.js
index 5898967..8161203 100644
--- a/tools/install.js
+++ b/tools/install.js
@@ -12,7 +12,7 @@ function whereis() {
     		var filename = arguments[j];
 	        var filePath = path.join(directories[i], filename);
 
-	        if (fs.existsSync(filePath)) {
+	        if (fs.existsSync(filePath) && fs.lstatSync(filePath).isFile()) {
 	            return filePath;
 	        }
 	    }
--
